=== magesuite/changelog/etc/changelog.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="module">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="changelog">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="tag" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="entry" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element type="xs:string" name="type"/>
																<xs:element type="xs:string" name="overview"/>
																<xs:element type="xs:string" name="description" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute type="xs:string" name="version" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="id"/>
						<xs:attribute type="xs:string" name="name"/>
						<xs:attribute type="xs:string" name="description"/>
						<xs:attribute type="xs:string" name="url"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== magesuite/changelog/Controller/Adminhtml/changelog.xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:MageSuite_Changelog:etc/changelog.xsd">
    <module
        id="Title"
        name="Title"
        description="$description"
        url="$url">
        <changelog>
            <tag version="1.0.0" date="2022-01-08">
                <entry>
                    <type>INIT</type>
                    <overview>Initial release</overview>
                    <description></description>
                </entry>
            </tag>
        </changelog>
    </module>
</config>

=== magesuite/changelog/etc/changelog.xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:MageSuite_Changelog:etc/changelog.xsd">
    <module
        id="MageSuite_Changelog"
        name="Magesuite_Changelog"
        description="This module allows to gather and display changelog entries from all compatible extensions."
        url="https://github.com/magesuite/changelog">
            <changelog>
                <tag version="1.0.0" date="2021-03-12">
                    <entry>
                        <type>INIT</type>
                        <overview>Initial release</overview>
                    </entry>
                </tag>
                <tag version="1.0.1" date="2022-05-11">
                    <entry>
                        <type>FIX</type>
                        <overview>Adjusted code to be compatible with php7</overview>
                    </entry>
                </tag>
                <tag version="1.0.2" date="2022-05-17">
                    <entry>
                        <type>FIX</type>
                        <overview>Refactored xsd file to be less strict</overview>
                    </entry>
                    <entry>
                        <type>FIX</type>
                        <overview>Fixed obtaining list of nodes from XML</overview>
                    </entry>
                </tag>
                <tag version="1.0.3" date="2022-05-18">
                    <entry>
                        <type>FIX</type>
                        <overview>Corrected integration test to support different order of extensions.</overview>
                    </entry>
                </tag>
            </changelog>
    </module>
</config>

=== magesuite/changelog/Test/Integration/_files/dummy_changelog.xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:MageSuite_Changelog:etc/changelog.xsd">
    <module
        id="Module_Dummy"
        name="Module_Dummy"
        description="This module is fake changelog for integration test purposes.">
        <changelog>
            <tag version="1.0.0" date="2021-03-12">
                <entry>
                    <type>INIT</type>
                    <overview>Initial release of dummy changelog</overview>
                </entry>
            </tag>
            <tag version="1.0.1" date="2022-05-11">
                <entry>
                    <type>FIX</type>
                    <overview>Dummy change</overview>
                </entry>
            </tag>
        </changelog>
    </module>
</config>
